services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
